language: cpp
compiler:
  - gcc
  - clang
before_script: qmake silverlock.pro -r
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - jake.petroules+travis@petroules.com
  email:
    on_success: change
    on_failure: always

