language: cpp
compiler:
  - gcc
  - clang
before_script: git submodule update --init --recursive && mkdir ../silverlock-build && cd ../silverlock-build && qmake ../silverlock/src/silverlock.pro -r
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - jake.petroules+travis@petroules.com
  email:
    on_success: change
    on_failure: always

