#ifndef CONFIG_H
#define CONFIG_H

#define PROJECT_ID "@PROJECT_ID@"
#define PROJECT_UUID "@PROJECT_UUID@"

#define PROJECT_NAME "@CMAKE_PROJECT_NAME@"
#define PROJECT_NAME_UNIX "@PROJECT_NAME_UNIX@"
#define PROJECT_SUMMARY "@PROJECT_SUMMARY@"
#define PROJECT_DESCRIPTION "@PROJECT_DESCRIPTION@"

#define PROJECT_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define PROJECT_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define PROJECT_VERSION_PATCH @PROJECT_VERSION_PATCH@
#define PROJECT_VERSION_BUILD @PROJECT_VERSION_BUILD@
#define PROJECT_VERSION "@PROJECT_VERSION@"
#define PROJECT_VERSION_CSV @PROJECT_VERSION_MAJOR@,@PROJECT_VERSION_MINOR@,@PROJECT_VERSION_PATCH@,@PROJECT_VERSION_BUILD@

#define PROJECT_VENDOR "@PROJECT_VENDOR@"
#define PROJECT_CONTACT "@PROJECT_CONTACT@"
#define PROJECT_COPYRIGHT "@PROJECT_COPYRIGHT@"
#define ORG_WEBSITE "@ORG_WEBSITE@"
#define ORG_DOMAIN "@ORG_DOMAIN@"

// Defines related to Windows .rc files
#define VER_FILEDESCRIPTION_STR     PROJECT_SUMMARY
#define VER_INTERNALNAME_STR        APP_DISPLAYNAME
#define VER_PRODUCTNAME_STR         APP_DISPLAYNAME
#define VER_COMPANYNAME_STR         PROJECT_VENDOR
#define VER_LEGALCOPYRIGHT_STR      PROJECT_COPYRIGHT // backslash xA9 for real (c) symbol...
#define VER_LEGALTRADEMARKS1_STR    "All Rights Reserved"
#define VER_LEGALTRADEMARKS2_STR    VER_LEGALTRADEMARKS1_STR
#define VER_COMPANYDOMAIN_STR       ORG_DOMAIN

#endif // CONFIG_H
