#ifndef CONFIG_H
#define CONFIG_H

#define PROJECT_ID "@PROJECT_ID@"
#define PROJECT_UUID "@PROJECT_UUID@"

#define PROJECT_SUMMARY "@PROJECT_SUMMARY@"
#define PROJECT_DESCRIPTION "@PROJECT_DESCRIPTION@"

#define SILVERLOCK_VERSION_MAJOR @SILVERLOCK_VERSION_MAJOR@
#define SILVERLOCK_VERSION_MINOR @SILVERLOCK_VERSION_MINOR@
#define SILVERLOCK_VERSION_PATCH @SILVERLOCK_VERSION_PATCH@
#define SILVERLOCK_VERSION_BUILD @SILVERLOCK_VERSION_BUILD@
#define SILVERLOCK_VERSION_SHORT "@SILVERLOCK_VERSION_SHORT@"
#define SILVERLOCK_VERSION_LONG "@SILVERLOCK_VERSION_LONG@"
#define SILVERLOCK_VERSION_CSV @SILVERLOCK_VERSION_MAJOR@,@SILVERLOCK_VERSION_MINOR@,@SILVERLOCK_VERSION_PATCH@,@SILVERLOCK_VERSION_BUILD@

#define SILVERLOCK_VENDOR "@SILVERLOCK_VENDOR@"
#define SILVERLOCK_CONTACT "@SILVERLOCK_CONTACT@"
#define SILVERLOCK_COPYRIGHT "@SILVERLOCK_COPYRIGHT@"
#define SILVERLOCK_WEBSITE "@SILVERLOCK_WEBSITE@"
#define SILVERLOCK_DOMAIN "@SILVERLOCK_DOMAIN@"

// Defines related to Windows .rc files
#define VER_FILEDESCRIPTION_STR     PROJECT_SUMMARY
#define VER_INTERNALNAME_STR        APP_DISPLAYNAME
#define VER_PRODUCTNAME_STR         APP_DISPLAYNAME
#define VER_COMPANYNAME_STR         SILVERLOCK_VENDOR
#define VER_LEGALCOPYRIGHT_STR      SILVERLOCK_COPYRIGHT // backslash xA9 for real (c) symbol...
#define VER_LEGALTRADEMARKS1_STR    "All Rights Reserved"
#define VER_LEGALTRADEMARKS2_STR    VER_LEGALTRADEMARKS1_STR
#define VER_COMPANYDOMAIN_STR       SILVERLOCK_DOMAIN

#endif // CONFIG_H
