# Gets system libraries such as compiler and C++ runtime DLLs
include(InstallRequiredSystemLibraries)

# Package version
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION ${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}.${CPACK_PACKAGE_VERSION_BUILD})

# CPack variables...
set(CPACK_SYSTEM_NAME ${CMAKE_SYSTEM_NAME})
set(CPACK_PACKAGE_ICON "${CMAKE_SOURCE_DIR}/res/app.icns")
set(CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
set(CPACK_PACKAGE_DESCRIPTION "${PROJECT_SUMMARY}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${PROJECT_SUMMARY} \n ${PROJECT_DESCRIPTION}")
set(CPACK_PACKAGE_VENDOR ${PROJECT_VENDOR})
set(CPACK_PACKAGE_CONTACT ${PROJECT_CONTACT})
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_SOURCE_DIR}/README.md")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/COPYING.md")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${CMAKE_BINARY_DIR}/dist")

# Filename
string(TOLOWER ${CPACK_SYSTEM_NAME} OS_CODE)
if(APPLE)
    set(OS_CODE "osx")
endif()

set(TARGET_ARCH ${CMAKE_TARGET_ARCHITECTURES})
if(CMAKE_TARGET_ARCHITECTURE_UNIVERSAL)
    set(TARGET_ARCH "universal")
endif()

set(CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME_UNIX}-${PROJECT_VERSION}-${OS_CODE}-${TARGET_ARCH}")

# Source package
if(WIN32)
    set(CPACK_SOURCE_GENERATOR "ZIP")
else()
    set(CPACK_SOURCE_GENERATOR "ZIP;TGZ;TBZ2")
endif()
set(CPACK_SOURCE_IGNORE_FILES ".git;.DS_Store;thumbs.db;CMakeLists.txt.user")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "${PROJECT_NAME_UNIX}-${PROJECT_VERSION}-src")

if(APPLE)
    set(CPACK_GENERATOR "DragNDrop")
    set(CPACK_COMPONENT_LIBRARIES_HIDDEN TRUE)

    #set(CPACK_DMG_DS_STORE "/Users/jakepetroules/Downloads/dmg_DS_Store")
    #set(CPACK_DMG_BACKGROUND_IMAGE "${CMAKE_SOURCE_DIR}/deploy/macx/dmg-background.png")
    set(CPACK_DMG_VOLUME_NAME "${CMAKE_PROJECT_NAME} ${PROJECT_VERSION}")
    set(CPACK_TOPLEVEL_TAG "dist")

    set(MACOSX_BUNDLE_BUNDLE_NAME "${CMAKE_PROJECT_NAME}")
    set(MACOSX_BUNDLE_BUNDLE_VERSION "${PROJECT_VERSION}")
    set(MACOSX_BUNDLE_GUI_IDENTIFIER "${PROJECT_ID}")
    set(MACOSX_BUNDLE_INFO_STRING "${PROJECT_NAME} ${PROJECT_VERSION}")
    set(MACOSX_BUNDLE_LONG_VERSION_STRING "Version ${PROJECT_VERSION}")
    set(MACOSX_BUNDLE_SHORT_VERSION_STRING "${PROJECT_VERSION}")
endif()

include(CPack)
