#ifndef SILVERLOCKLIB_GLOBAL_H
#define SILVERLOCKLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SILVERLOCKLIB_LIBRARY)
#  define SILVERLOCKLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SILVERLOCKLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SILVERLOCKLIB_GLOBAL_H
