#ifndef VERSION_H_SL
#define VERSION_H_SL

#define VER_FILEVERSION             @PROJECT_VERSION_MAJOR@,@PROJECT_VERSION_MINOR@,@PROJECT_VERSION_PATCH@,@PROJECT_VERSION_BUILD@
#define VER_PRODUCTVERSION          @PROJECT_VERSION_MAJOR@,@PROJECT_VERSION_MINOR@,@PROJECT_VERSION_PATCH@,@PROJECT_VERSION_BUILD@
#define VER_FILEVERSION_STR         "@PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@.@PROJECT_VERSION_PATCH@.@PROJECT_VERSION_BUILD@"
#define VER_PRODUCTVERSION_STR      "@PROJECT_VERSION@"
#define VER_ORIGINALFILENAME_STR    "@PROJECT_NAME_UNIX@.exe"

#define APP_DISPLAYNAME             "@PROJECT_NAME@"
#define APP_UNIXNAME                "@PROJECT_NAME_UNIX@"
#define APP_BUNDLEID                "@PROJECT_ID@"
#define VER_FILEDESCRIPTION_STR     APP_DISPLAYNAME
#define VER_INTERNALNAME_STR        APP_DISPLAYNAME
#define VER_PRODUCTNAME_STR         APP_DISPLAYNAME

#define VER_COMPANYNAME_STR         "@PROJECT_VENDOR@"
#define VER_LEGALCOPYRIGHT_STR      "@PROJECT_COPYRIGHT@" // backslash xA9 for real (c) symbol...
#define VER_LEGALTRADEMARKS1_STR    "All Rights Reserved"
#define VER_LEGALTRADEMARKS2_STR    VER_LEGALTRADEMARKS1_STR
#define VER_COMPANYDOMAIN_STR       "@ORG_DOMAIN@"

#define VER_APP_UUID                "@PROJECT_UUID@"

#endif // VERSION_H_SL
